language: node_js
node_js:
  - "node"
env:
  - NODE_ENV=development
  - NODE_ENV=production
  - NODE_ENV=testing
install:
  - npm install
before_script:
  - bash setup-config-for-travis.sh
script: 
  - npm run build
